name: CD Front-end

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Railway
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest
      - name: Deploy to Railway
        working-directory: sgcmapp/
        run: railway up --detach --service sgcmapp
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_FRONT }}
